# Copyright (C) 2009 Daniel Esplin
# Part of the Virtual Kingdoms the Game project. http://www.virtualkingdoms.net/

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# or at your option any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY.

# See the COPYING file for more details.

# Generated by Sassafras
# complement1
COMPLEMENT1_DARK = rgb(64, 0, 22)
COMPLEMENT1_LIGHT = rgb(192, 128, 150)
COMPLEMENT1_DARKER = rgb(38, 0, 13)
COMPLEMENT1_LIGHTEST = rgb(242, 230, 234)
COMPLEMENT1_LIGHTER = rgb(217, 179, 192)
COMPLEMENT1_MID = rgb(128, 0, 45)
COMPLEMENT1_DARKEST = rgb(13, 0, 4)

# complement2
COMPLEMENT2_DARK = rgb(0, 64, 20)
COMPLEMENT2_LIGHT = rgb(128, 192, 148)
COMPLEMENT2_DARKER = rgb(0, 38, 12)
COMPLEMENT2_LIGHTEST = rgb(230, 242, 234)
COMPLEMENT2_LIGHTER = rgb(179, 217, 191)
COMPLEMENT2_MID = rgb(0, 128, 41)
COMPLEMENT2_DARKEST = rgb(0, 13, 4)

# base
BASE_DARK = rgb(0, 64, 0)
BASE_LIGHT = rgb(128, 192, 128)
BASE_DARKER = rgb(0, 38, 0)
BASE_LIGHTEST = rgb(230, 242, 230)
BASE_LIGHTER = rgb(179, 217, 179)
BASE_MID = rgb(0, 128, 0)
BASE_DARKEST = rgb(0, 13, 0)

