Shoes.setup do
  gem 'activerecord'
  gem 'activesupport'
  gem 'curb'
end

require 'activerecord'
require 'curb'
require 'app/models/game'

VK_SERVER_URL = 'http://localhost:3000'
GAME_ID = 2
DBPATH = "db/db.sqlite3"

# Generated by Sassafras
# complement1
COMPLEMENT1_DARK = rgb(64, 0, 22)
COMPLEMENT1_LIGHT = rgb(192, 128, 150)
COMPLEMENT1_DARKER = rgb(38, 0, 13)
COMPLEMENT1_LIGHTEST = rgb(242, 230, 234)
COMPLEMENT1_LIGHTER = rgb(217, 179, 192)
COMPLEMENT1_MID = rgb(128, 0, 45)
COMPLEMENT1_DARKEST = rgb(13, 0, 4)

# complement2
COMPLEMENT2_DARK = rgb(0, 64, 20)
COMPLEMENT2_LIGHT = rgb(128, 192, 148)
COMPLEMENT2_DARKER = rgb(0, 38, 12)
COMPLEMENT2_LIGHTEST = rgb(230, 242, 234)
COMPLEMENT2_LIGHTER = rgb(179, 217, 191)
COMPLEMENT2_MID = rgb(0, 128, 41)
COMPLEMENT2_DARKEST = rgb(0, 13, 4)

# base
BASE_DARK = rgb(0, 64, 0)
BASE_LIGHT = rgb(128, 192, 128)
BASE_DARKER = rgb(0, 38, 0)
BASE_LIGHTEST = rgb(230, 242, 230)
BASE_LIGHTER = rgb(179, 217, 179)
BASE_MID = rgb(0, 128, 0)
BASE_DARKEST = rgb(0, 13, 0)


ActiveRecord::Base.establish_connection({
  :adapter => 'sqlite3',
  :dbfile => DBPATH,
})

class VirtualKingdomsGame < Shoes
  # show_log
  @@email = ''
  @@password = ''

  def index
    title "Virtual Kingdoms: the Game"
    e, pw = '', ''
    stack do
      flow do
        para "Email:"
        e = edit_line
      end
      flow do
        para "Password:"
        pw = edit_line :secret => true
      end
      flow do
        button "Let the Adventure Begin", :width => 300 do
          para "Downloading... please be patient"
          @@email = CGI.escape(e.text)
          @@password = CGI.escape(pw.text)
          params = "id=#{GAME_ID}&email=#{@@email}&password=#{@@password}"
          download "#{VK_SERVER_URL}/pages/download?#{params}", :save => DBPATH do |r|
            if (200..300).include?(r.response.headers['Status'].to_i)
              visit '/game'
            else
              alert File.read(DBPATH)
              exit
            end
          end
        end
      end
    end
  end

  def game
    stack do
      para 'Welcome to the Jungle'
      para Game.all.inspect
      Game.create(:name => "#{rand(1000)}")
      para Game.all.map {|g| g.name}.join(' ')
      button "Quit" do
        para "saving..."
        params = "id=#{GAME_ID}&email=#{@@email}&password=#{@@password}"
        c = Curl::Easy.new("#{VK_SERVER_URL}/pages/upload?#{params}")
        c.multipart_form_post = true
        c.http_post(Curl::PostField.file('game[data]', DBPATH))
        if (200..300).include?(c.response_code)
          File.delete(DBPATH)
          exit
        else
          para "Error"
        end
      end
    end
  end

  def field
    title "vk"
    stack :width => 350, :height => 350 do
      background BASE_LIGHT
      flow :width => 340, :displace_left => 4, :displace_top => 4 do
        25.times do |i|
          stack :width => 68, :height => 68 do
            if i == 25 / 2
              border COMPLEMENT1_LIGHTER, :strokewidth => 5
            else
              border COMPLEMENT2_LIGHTER
            end
            image "images/terrains/00ff00.png", :width => 60, :height => 60, :margin => [2, 2, 0, 0], :displace_left => 3, :displace_top => 3
          end
        end
      end
    end
  end

  url '/', :field
  url '/i', :index
  url '/game', :game
end

Shoes.app
